# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passage',
            fields=[
                ('passageLink', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('passageTitle', models.CharField(blank=True, max_length=100)),
                ('passageBody', models.TextField()),
                ('passageDate', models.DateField(auto_now=True)),
                ('passageSource', models.CharField(choices=[('message', '短信'), ('email', '邮件'), ('friendCicle', '朋友圈')], max_length=20)),
                ('passageLabel', models.CharField(choices=[('Food', '食品安全'), ('newTech', '新科技'), ('health', '健康养生')], max_length=20)),
            ],
        ),
    ]
