# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPassage',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('label', models.CharField(choices=[('Food', '食品安全'), ('health', '健康养生'), ('newTech', '新科技')], max_length=20)),
                ('image', models.ImageField(default='blogImages/no-img.jpeg', upload_to='blogImages/')),
                ('author', models.CharField(blank=True, default='匿名用户', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='passage',
            fields=[
                ('passageLink', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('passageTitle', models.CharField(blank=True, default='无标题', max_length=100)),
                ('passageBody', models.TextField()),
                ('passageDate', models.DateField(auto_now=True)),
                ('passageSource', models.CharField(choices=[('email', '邮件'), ('message', '短信'), ('friendCicle', '朋友圈')], max_length=20)),
                ('passageLabel', models.CharField(choices=[('Food', '食品安全'), ('health', '健康养生'), ('newTech', '新科技')], max_length=20)),
                ('passagePhone', models.CharField(blank=True, max_length=20)),
                ('passageAppendix', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-passageDate'],
            },
        ),
        migrations.CreateModel(
            name='showingPassage',
            fields=[
                ('passageTitle', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('passageBody', models.TextField(blank=True, default='无内容', null=True)),
            ],
        ),
    ]
