# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpassage',
            name='label',
            field=models.CharField(choices=[('newTech', '新科技'), ('Food', '食品安全'), ('health', '健康养生')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageLabel',
            field=models.CharField(choices=[('newTech', '新科技'), ('Food', '食品安全'), ('health', '健康养生')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageSource',
            field=models.CharField(choices=[('message', '短信'), ('friendCicle', '朋友圈'), ('email', '邮件')], max_length=20),
        ),
    ]
