# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20170324_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='showingPassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageSource',
            field=models.CharField(choices=[('message', '短信'), ('friendCicle', '朋友圈'), ('email', '邮件')], max_length=20),
        ),
        migrations.AddField(
            model_name='showingpassage',
            name='passages',
            field=models.ManyToManyField(to='center.passage'),
        ),
    ]
