# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20170326_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPassage',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('label', models.CharField(choices=[('newTech', '新科技'), ('health', '健康养生'), ('Food', '食品安全')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['-passageDate']},
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageLabel',
            field=models.CharField(choices=[('newTech', '新科技'), ('health', '健康养生'), ('Food', '食品安全')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageSource',
            field=models.CharField(choices=[('friendCicle', '朋友圈'), ('email', '邮件'), ('message', '短信')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageTitle',
            field=models.CharField(blank=True, default='无标题', max_length=100),
        ),
    ]
