# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20170327_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpassage',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='showingpassage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='showingpassage',
            name='passages',
        ),
        migrations.AddField(
            model_name='showingpassage',
            name='passageBody',
            field=models.TextField(blank=True, default='无内容', null=True),
        ),
        migrations.AddField(
            model_name='showingpassage',
            name='passageTitle',
            field=models.CharField(default='nothing', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpassage',
            name='label',
            field=models.CharField(choices=[('health', '健康养生'), ('Food', '食品安全'), ('newTech', '新科技')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageLabel',
            field=models.CharField(choices=[('health', '健康养生'), ('Food', '食品安全'), ('newTech', '新科技')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageSource',
            field=models.CharField(choices=[('message', '短信'), ('email', '邮件'), ('friendCicle', '朋友圈')], max_length=20),
        ),
    ]
