# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_auto_20170410_1722'),
        ('center', '0007_auto_20170410_1640'),
    ]

    operations = [
    ]
