# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_auto_20170415_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpassage',
            name='label',
            field=models.CharField(choices=[('Food', '食品安全'), ('newTech', '新科技'), ('health', '健康养生')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageLabel',
            field=models.CharField(choices=[('Food', '食品安全'), ('newTech', '新科技'), ('health', '健康养生')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageSource',
            field=models.CharField(choices=[('message', '短信'), ('email', '邮件'), ('friendCicle', '朋友圈')], max_length=20),
        ),
    ]
