# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_auto_20170415_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpassage',
            name='author',
            field=models.CharField(blank=True, default='匿名用户', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpassage',
            name='label',
            field=models.CharField(choices=[('newTech', '新科技'), ('Food', '食品安全'), ('health', '健康养生')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageLabel',
            field=models.CharField(choices=[('newTech', '新科技'), ('Food', '食品安全'), ('health', '健康养生')], max_length=20),
        ),
    ]
