# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_auto_20170417_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpassage',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='passageSource',
            field=models.CharField(choices=[('friendCicle', '朋友圈'), ('email', '邮件'), ('message', '短信')], max_length=20),
        ),
    ]
